platform :ios, '9.0'

target 'ChiMusiciansConnect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChiMusiciansConnect

pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Alamofire', '~> 4.7'
pod 'SideMenu'
pod 'FBSDKCoreKit', :inhibit_warnings => true
pod 'FBSDKShareKit', :inhibit_warnings => true
pod 'FBSDKLoginKit', :inhibit_warnings => true
pod 'Bolts', :inhibit_warnings => true

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
